credentials:
  system:
    domainCredentials:
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "Agent/Build:derekpedersen"
      - "Agent/Configure:derekpedersen"
      - "Agent/Connect:derekpedersen"
      - "Agent/Create:derekpedersen"
      - "Agent/Delete:derekpedersen"
      - "Agent/Disconnect:derekpedersen"
      - "Credentials/Create:derekpedersen"
      - "Credentials/Delete:derekpedersen"
      - "Credentials/ManageDomains:derekpedersen"
      - "Credentials/Update:derekpedersen"
      - "Credentials/View:derekpedersen"
      - "Job/Build:derekpedersen"
      - "Job/Cancel:derekpedersen"
      - "Job/Configure:derekpedersen"
      - "Job/Create:derekpedersen"
      - "Job/Delete:derekpedersen"
      - "Job/Discover:derekpedersen"
      - "Job/Move:derekpedersen"
      - "Job/Read:anonymous"
      - "Job/Read:authenticated"
      - "Job/Read:derekpedersen"
      - "Job/Workspace:derekpedersen"
      - "Lockable Resources/Reserve:derekpedersen"
      - "Lockable Resources/Unlock:derekpedersen"
      - "Lockable Resources/View:derekpedersen"
      - "Overall/Administer:derekpedersen"
      - "Overall/Read:authenticated"
      - "Overall/Read:derekpedersen"
      - "Run/Delete:derekpedersen"
      - "Run/Replay:derekpedersen"
      - "Run/Update:derekpedersen"
      - "SCM/Tag:derekpedersen"
      - "View/Configure:derekpedersen"
      - "View/Create:derekpedersen"
      - "View/Delete:derekpedersen"
      - "View/Read:anonymous"
      - "View/Read:authenticated"
      - "View/Read:derekpedersen"
  clouds:
  - kubernetes:
      containerCap: 10
      containerCapStr: "10"
      jenkinsTunnel: "jenkins-1597965510-agent:50000"
      jenkinsUrl: "http://jenkins-1597965510:8080"
      maxRequestsPerHost: 32
      maxRequestsPerHostStr: "32"
      name: "kubernetes"
      namespace: "default"
      serverUrl: "https://kubernetes.default"
      templates:
      - containers:
        - alwaysPullImage: true
          args: "^${computer.jnlpmac} ^${computer.name}"
          command: "/bin/sh -c"
          envVars:
          - containerEnvVar:
              key: "JENKINS_URL"
              value: "http://jenkins-1597965510.default.svc.cluster.local:8080"
          image: "us.gcr.io/sleipnir/build-golang:latest"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jnlp"
          resourceLimitCpu: ".5"
          resourceLimitMemory: "512Mi"
          resourceRequestCpu: ".1"
          resourceRequestMemory: "512Mi"
          workingDir: "/home/jenkins"
        hostNetwork: false
        idleMinutes: 15
        idleMinutesStr: "15"
        instanceCap: 5
        instanceCapStr: "5"
        label: "build-golang-stable"
        name: "golang"
        nodeUsageMode: "NORMAL"
        podRetention: "onFailure"
        serviceAccount: "default"
        slaveConnectTimeout: 600
        slaveConnectTimeoutStr: "600"
        volumes:
        - hostPathVolume:
            hostPath: "/var/run/docker.sock"
            mountPath: "/var/run/docker.sock"
        yamlMergeStrategy: "override"
      - containers:
        - alwaysPullImage: true
          args: "^${computer.jnlpmac} ^${computer.name}"
          command: "/bin/sh -c"
          image: "us.gcr.io/sleipnir/build-node:latest"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jnlp"
          ttyEnabled: true
          workingDir: "/home/jenkins"
        hostNetwork: false
        idleMinutes: 15
        idleMinutesStr: "15"
        instanceCap: 5
        instanceCapStr: "5"
        label: "build-node-stable"
        name: "node"
        podRetention: "onFailure"
        slaveConnectTimeout: 600
        slaveConnectTimeoutStr: "600"
        volumes:
        - hostPathVolume:
            hostPath: "/var/run/docker.sock"
            mountPath: "/var/run/docker.sock"
        yamlMergeStrategy: "override"
      - containers:
        - alwaysPullImage: true
          args: "^${computer.jnlpmac} ^${computer.name}"
          command: "/bin/sh -c"
          image: "us.gcr.io/sleipnir/build-jenkins-base:latest"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jnlp"
          ttyEnabled: true
          workingDir: "/home/jenkins/agent"
        hostNetwork: false
        idleMinutes: 15
        idleMinutesStr: "15"
        instanceCap: 5
        instanceCapStr: "5"
        label: "build-base-stable"
        name: "jenkins"
        podRetention: "onFailure"
        slaveConnectTimeout: 600
        slaveConnectTimeoutStr: "600"
        volumes:
        - hostPathVolume:
            hostPath: "/var/run/docker.sock"
            mountPath: "/var/run/docker.sock"
        yamlMergeStrategy: "override"
      - containers:
        - alwaysPullImage: true
          args: "^${computer.jnlpmac} ^${computer.name}"
          command: "/bin/sh -c"
          image: "us.gcr.io/sleipnir/build-dotnetcore:latest"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jnlp"
          ttyEnabled: true
          workingDir: "/home/jenkins/agent"
        hostNetwork: false
        idleMinutes: 15
        idleMinutesStr: "15"
        instanceCap: 5
        instanceCapStr: "5"
        label: "build-dotnetcore-stable"
        name: "dotnet-core"
        podRetention: "onFailure"
        slaveConnectTimeout: 600
        slaveConnectTimeoutStr: "600"
        volumes:
        - hostPathVolume:
            hostPath: "/var/run/docker.sock"
            mountPath: "/var/run/docker.sock"
        yamlMergeStrategy: "override"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "jenkins.security.QueueItemAuthenticatorMonitor"
  labelAtoms:
  - name: "master"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    github:
      clientID: "725008ee2da8b3bd533e"
      clientSecret: "{AQAAABAAAAAwBXHX7uOUHMsTcCAECtvlRU9fvvWe60BGjYVs1xI6/QZERzHm52/0/ufdEdJW1ZHaXhjLqmsUc2RvDdtUSgWP8A==}"
      githubApiUri: "https://api.github.com"
      githubWebUri: "https://github.com"
      oauthScopes: "read:org,user:email,repo"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  sSHD:
    port: -1
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  casCGlobalConfig:
    configurationPath: "https://raw.githubusercontent.com/derekpedersen/gke-jenkins/master/JenkinsConfig.yaml"
  defaultFolderConfiguration:
    healthMetrics:
    - worstChildHealthMetric:
        recursive: true
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    configs:
      manageHooks: false
      name: "github.com"
    hookUrl: "https://jenkins.pedersen.io/github-webhook/"
  gitSCM:
    createAccountBasedOnEmail: false
    globalConfigEmail: "jenkins@pedersen.io"
    globalConfigName: "jenkins"
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  location:
    adminAddress: "jenkins@pedersen.io"
    url: "https://jenkins.pedersen.io/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
