apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        - containerPort: 50000
        resources:
          limits:
            cpu: "100m"
            memory: "750Mi"
          requests:
            cpu: "10m"
            memory: "500Mi"
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        env:
        - name: JENKINS_OPTS
          valueFrom:
            secretKeyRef:
              name: jenkins
              key: options
        - name: JAVA_OPTS
          value: '-Xmx1400m'
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home-dir
      volumes:
      - name: jenkins-home-dir
        gcePersistentDisk:
          pdName: jenkins-home-dir
          fsType: ext4
          partition: 1
