apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: us.gcr.io/%GCLOUD_PROJECT_ID%/jenkins-custom:%GIT_COMMIT_SHA%
        ports:
        - containerPort: 8080
        - containerPort: 50000
        resources:
          limits:
            cpu: "50m"
            memory: "1000Mi"
          requests:
            cpu: "10m"
            memory: "500Mi"
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 1200
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        env:
        - name: JENKINS_OPTS
          valueFrom:
            secretKeyRef:
              name: jenkins
              key: options
        - name: JAVA_OPTS
          value: '-Xmx1400m'
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home-dir
      volumes:
      - name: jenkins-home-dir
        gcePersistentDisk:
          pdName: jenkins-home-dir
          fsType: ext4
          partition: 1
          